const allProductsData = {
    allProductsData : [
    {
        id: 1,
        discount: 50,
        img: "./assets/flash-deals/flash-1.png",
        name: "Shoes",
        price: 100,
      },
      {
        id: 2,
        discount: 40,
        img: "./assets/flash-deals/flash-2.png",
        name: "Watch",
        price: 20,
      },
      {
        id: 3,
        discount: 40,
        img: "./assets/flash-deals/flash-3.png",
        name: "Smart Mobile Black",
        price: 200,
      },
      {
        id: 4,
        discount: 40,
        img: "./assets/flash-deals/flash-4.png",
        name: "Smart Watch Black",
        price: 50,
      },
      {
        id: 5,
        discount: 50,
        img: "./assets/flash-deals/flash-5.png",
        name: "Shoes",
        price: 100,
      },
      {
        id: 6,
        discount: 50,
        img: "./assets/flash-deals/flash-6.jpg",
        name: "Shoes",
        price: 100,
      },
        {
          id: 7,
          img: "./assets/shop-items/shops-1.png",
          name: "Mapple Earphones",
          price: "180",
          discount: "25",
        },
        {
          id: 8,
          img: "./assets/shop-items/shops-2.png",
          name: "Vivo android one",
          price: "120",
          discount: "10",
        },
        {
          id: 9,
          img: "./assets/shop-items/shops-3.png",
          name: "Sony Light",
          price: "20",
          discount: "50 ",
        },
        {
          id: 10,
          img: "./assets/shop-items/shops-4.png",
          name: "Iphone",
          price: "999",
          discount: "10 ",
        },
        {
          id: 11,
          img: "./assets/shop-items/shops-5.png",
          name: "Ceats wireless earphone",
          price: "80",
          discount: "20 ",
        },
        {
          id: 12,
          img: "./assets/shop-items/shops-7.png",
          name: "Redimi Phone",
          price: "400",
          discount: "20 ",
        },
        {
          id: 13,
          img: "./assets/shop-items/shops-8.png",
          name: "Xeats Bluetooth earphones",
          price: "60",
          discount: "5 ",
        },
        {
          id: 14,
          img: "./assets/shop-items/shops-9.png",
          name: "Airpod",
          price: "120",
          discount: "10",
        },
        {
          id: 15,
          img: "./assets/shop-items/shops-10.png",
          name: "Silver Cap",
          price: "5",
          discount: "2",
        }
      ]}

export default allProductsData;